### ISSUE TITLE
Document how to add processor(s)?

### ISSUE THREAD

**Issue by kbsali** [theorchard/monolog-cascade#35]
Hi,

i see from the code that you can setup up processors,
how would you add that sort of processor with yaml configuration?
```php
$logger = new Logger('my_logger');
$logger->pushHandler(new StreamHandler('./api.log', Logger::INFO));
$logger->pushProcessor(function ($record) {
    $record['extra']['dummy'] = 'Hello world!';

    return $record;
});
```

Thanks.

**Comment by kbsali** [comment]
got part of the answer looking at the testing fixtures :+1: 

```
...
processors:
    web_processor:
        class: 'Monolog\Processor\WebProcessor'
...
```
The class is indeed invoked, but I cannot see any extra fields in the logs...

**Comment by rantonmattei** [comment]
You probably are missing the last line
```yaml
processors:
    web_processor:
        class: 'Monolog\Processor\WebProcessor'
handlers:
    console:
        class: Monolog\Handler\StreamHandler
        level: DEBUG
        stream: php://stdout
loggers:
    hi:
        handlers: [console]
        processors: [web_processor]
```
