### ISSUE TITLE
PHP error: "Cannot determine default value for internal functions ..."

### ISSUE THREAD

**Issue by kafene** [theorchard/monolog-cascade#37]
Example config:

```yaml
handlers:
    mongodb:
        class: Monolog\Handler\MongoDBHandler
        mongo:
            class: MongoClient
            server: mongodb://example.com:27017
        database: doctrine
        collection: logs
loggers:
    doctrine:
        handlers: [mongodb]
```

Which results in the following error:

> `ReflectionException: Cannot determine default value for internal functions in /path/to/vendor/theorchard/monolog-cascade/src/Config/Loader/ClassLoader/Resolver/ConstructorResolver.php on line 105`

I managed to get it working alrght:

https://github.com/kafene/monolog-cascade/commit/429ebaa3b8c2cfd25e985a5d4e84c886ddb66b7e

I'm not sure if this is the most appropriate fix, let me know if you'd like a PR.
