### ISSUE TITLE
Illegal string offset 'disable_existing_loggers' 

### ISSUE THREAD

**Issue by mdeletrez** [theorchard/monolog-cascade#41]
Illegal string offset 'disable_existing_loggers' in vendor/theorchard/monolog-cascade/src/Config.php:99

$this->options seems to be a string having the path of the config file

```
        $path = APPLICATION_PATH . '/configs/monolog/cascade/testcontroller.yaml';
        //echo $path."\n";
        Cascade::fileConfig($path);
        
        Cascade::getLogger('myApp')->info('Well, that works!');
        Cascade::getLogger('myApp')->error('Maybe not...');
```
```
formatters:
    dashed:
        class: Monolog\Formatter\LineFormatter
        format: "%datetime%-%channel%.%level_name% - %message%\n"
handlers:
    console:
        class: Monolog\Handler\StreamHandler
        level: DEBUG
        formatter: dashed
        stream: php://stdout
    info_file_handler:
        class: Monolog\Handler\StreamHandler
        level: INFO
        formatter: dashed
        stream: /tmp/example_info.log
processors:
    introspection_processor:
        class: Monolog\Processor\IntrospectionProcessor
loggers:
    myApp:
        handlers: [console, info_file_handler]
        processors: [introspection_processor]
```
