### ISSUE TITLE
SwiftMailerHandler configuration

### ISSUE THREAD

**Issue by nayanap** [theorchard/monolog-cascade#59]
I think this is a great library making life easy in setting up logs. Although, I am trying to configure SwiftMailerHandler as one of the handlers to send alerts for errors. I am having issues in doing so. Do you have samples or documentation on how to set it up ?

**Comment by rantonmattei** [comment]
Hello,

You can look into setting up handlers that take object as arguments in their constructor:
You have an example here with the `RavenHandler`
https://github.com/theorchard/monolog-cascade/blob/master/examples/dependency_config.yml

It should look something like:
```yaml

handlers:
    swift:
        class: Monolog\Handler\SwiftMailerHandler
        mailer:
            class: Swift_Mailer
            transport: 
                class: Swift_SmtpTransport
                # Below is optional cause Cascade should pick up
                # default values for you
                #host: '127.0.0.1'
                #port: 25
        message:
            class: Swift_Message
            subject: 'Hello'
            body: 'How are you?'
        level: DEBUG
loggers:
    mylogger:
        handlers: [swift]
```
This has not been tested I just put it together by looking at different params of the constructors
`SwiftMailerHandler` construtor takes `$mailer` and `$message` as required parameters.
`$mailer` being an object (of `Swift_Mailer` type), you have to provide its contructor params as well.

From the ReadMe:

> Note: If you would like to use objects as parameters for your handlers, you can pass a class name (using the class option) with the corresponding arguments just like you would configure your handler. Cascade recursively instantiates and loads those objects as it parses the config file. See this sample config file.

Param names in your config just have to match the param names from the constructor.

I hope this helps.
