### ISSUE TITLE
YAML config file ignored

### ISSUE THREAD

**Issue by zwiebelspaetzle** [theorchard/monolog-cascade#84]
Cascade appears to be ignoring the config file.

I'm using the example code with a change in log level for testing (see code below).  However,  none of the expected behaviors are happening:
- console messages aren't using the `dashed` format
- file `./example_info.log` isn't written
- console INFO message is displayed, though log level is set to ERROR

If I intentionally set a bad path to config file, I get the expected `Illegal string offset` errors.

Here is my config file:
```
formatters:
    dashed:
        class: Monolog\Formatter\LineFormatter
        format: "%datetime%-%channel%.%level_name% - %message%\n"
handlers:
    console:
        class: Monolog\Handler\StreamHandler
        level: ERROR
        formatter: dashed
        processors: [memory_processor]
        stream: php://stdout
    info_file_handler:
        class: Monolog\Handler\StreamHandler
        level: INFO
        formatter: dashed
        stream: ./example_info.log
processors:
    web_processor:
        class: Monolog\Processor\WebProcessor
    memory_processor:
        class: Monolog\Processor\MemoryUsageProcessor
loggers:
    myLogger:
        handlers: [console, info_file_handler]
        processors: [web_processor]
```

and my PHP:
```
<?php

include 'vendor/autoload.php';

use Cascade\Cascade;

// configure your loggers
Cascade::fileConfig('config.yaml');

Cascade::getLogger('myApp')->info('Well, that works!');
Cascade::getLogger('myApp')->error('Maybe not...');
```

and `composer.json`:
```
{
    "require": {
        "theorchard/monolog-cascade": "^0.5.0"
    }
}
```
