### ISSUE TITLE
Rollbar configuration example

### ISSUE THREAD

**Issue by thefuriouscoder** [theorchard/monolog-cascade#86]
Hello,

it is possible to use monolog-cascade to configure the rollbar handler, I would like to configure all handlers using the yml config file, but I don't know if it's possible, even using the dependency config example, now, I'm using the Rollbar handler as follows:
```
Cascade::fileConfig(__DIR__ . '/config/dev/log.yml');
Rollbar::init([
    'access_token' => 'supercecretaccesstoken',
    'environment' => 'development'
]);
Cascade::getLogger('daemon')->pushHandler(
    new RollbarHandler(Rollbar::logger(), \Monolog\Logger::ERROR)
);

```
and my config file looks like that:
```
formatters:
  dashed:
    class: Monolog\Formatter\LineFormatter
    format: "%datetime% - [%level_name%][%extra.process_id%] - %message%\n"
handlers:
  logfile:
    class: Monolog\Handler\StreamHandler
    level: INFO
    formatter: dashed
    processors: [memory_processor,pid_processor]
    stream: /tmp/daemon.log
processors:
  memory_processor:
    class: Monolog\Processor\MemoryUsageProcessor
  pid_processor:
    class: Monolog\Processor\ProcessIdProcessor
loggers:
  daemon:
    handlers: [logfile]

```

Hope you can help me.

Thanks in advance.
Diego.
