### ISSUE TITLE
Public property starts uppercase not possible

### ISSUE THREAD

**Issue by kristi5** [theorchard/monolog-cascade#89]
This is part of my yaml file.

```
...
handlers:
  phpmailer_handler:
    class: MonologPHPMailer\PHPMailerHandler
    mailer:
      class: PHPMailer\PHPMailer\PHPMailer
      exceptions: true
      SMTPAuth: true
      Username: 'user'
      Password: 'password'
      isHTML: true
      isSMTP:
...
```

Setting Username, Password, SMTPAuth properties in following YAML ends with error:

```
Fatal error: Uncaught Symfony\Component\OptionsResolver\Exception\UndefinedOptionsException: The options "password", "sMTPAuth", "username" do not exist. Defined options are: "isHTML", "isSMTP". in .....
```
How can i set public properties or call methods starting with uppercase letter?
